# Generated by Django 4.2.7 on 2023-12-20 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_notification_following_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='static_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
