# Generated by Django 4.2.7 on 2023-12-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_quiz_leaderborad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshop_gallery/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='workshop_gallery/videos/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='accounts.workshop')),
            ],
        ),
    ]
