# Generated by Django 4.2.7 on 2023-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('expert', 'Expert'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
